# Data configuration
data:
  local_dir: /content/data/flower-102
  dataset_url: https://www.robots.ox.ac.uk/~vgg/data/flowers/102/102flowers.tgz
  num_batches: 7
  train_batches: [0, 1, 2, 3, 4]
  val_batches: [5]
  test_batches: [6]

dataset:
  train_split: 0.7
  val_split: 0.2
  test_split: 0.1
  random_seed: 42
  input_shape: [32, 32, 3]
  num_classes: 102

# Training configuration
training:
  epochs: 13
  batch_size: 32
  optimizer:
    name: Adam
    lr: 0.001
  loss: CrossEntropyLoss
  metrics:
    - accuracy
    - f1_score

# Model configuration
model:
  name: resnet18
  pretrained: False
  num_classes: 102
  freeze_base: False

# Logging configuration
logging:
  level: INFO
  file: /content/logs/training.log
  format: '%(asctime)s - %(levelname)s - %(message)s'

# Artifacts configuration
artifacts:
  output_dir: /content/artifacts
  save_best_model: True
  save_logs: True
  save_metrics: True
