# Data configuration
data:
  local_dir: /content/data
  dataset_url: https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz

# Training configuration
training:
  epochs: 100
  batch_size: 32
  optimizer:
    name: adam
    lr: 0.001
  loss: cross_entropy
  metrics:
    - accuracy
    - f1_score

# Model configuration
model:
  name: resnet18
  pretrained: False
  num_classes: 100
  freeze_base: False

# Logging configuration
logging:
  level: INFO
  file: /content/logs/training.log
  format: '%(asctime)s - %(levelname)s - %(message)s'

# Artifacts configuration
artifacts:
  output_dir: /content/artifacts
  save_best_model: True
  save_logs: True
  save_metrics: True
